# Generated by Django 5.1.2 on 2024-10-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_company_created_at_alter_company_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
