# Generated by Django 5.1.2 on 2024-10-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_company_unique_hash_alter_expense_unique_hash_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revenue',
            old_name='expense_category',
            new_name='revenue_category',
        ),
    ]
